### ISSUE TITLE
How to visualize results

### ISSUE THREAD

**Issue by jpdz** [facebookresearch/DetectAndTrack#10]
Hi! We have some questions while trying to use the model.
We are unable to run the test script. 
python launch.py \
	--cfg configs/video/2d_best/01_R101_best_hungarian-4GPU.yaml \
	--mode test \
	TEST.WEIGHTS pretrained_models/configs/video/2d_best/01_R101_best_hungarian.yaml/model_final.pkl
The error is shown below
![472259587126319729](https://user-images.githubusercontent.com/21374582/41751437-18947058-7576-11e8-8aaa-ef2c09934065.png)

And how to visualize the results of this model?

**Comment by rohitgirdhar** [comment]
As the message suggests, it's not able to find the pre-trained model at the expected location. Did you download the model and store at the location in the log message?

For visualization you can use/adapt `tools/visualize_results_v2.py`.

**Comment by jpdz** [comment]
Thank you for your answer. Finally I can visualize the results. 
Here is another problem which is similar to the first issue, can you share the script which can now detect and track for a single video, without evaluating it?
Really appreciate~

**Comment by rohitgirdhar** [comment]
Great. The other issue is tracked in https://github.com/facebookresearch/DetectAndTrack/issues/6.
