### ISSUE TITLE
How can I integrate Detectron with this tracking algorithm?

### ISSUE THREAD

**Issue by cppntn** [facebookresearch/DetectAndTrack#16]
What parts of this repository do i need to interface the tracking part with the results obtained running detectron on video frames? 

Thanks

**Comment by rohitgirdhar** [comment]
Most of the tracking code is contained in the [`lib/core/tracking_engine.py`](https://github.com/facebookresearch/DetectAndTrack/blob/master/lib/core/tracking_engine.py)
