### ISSUE TITLE
Regarding the type of objects for tracking.

### ISSUE THREAD

**Issue by imnaren142** [facebookresearch/DetectAndTrack#18]
Can we use this tracker for any type of objects or only for human body?? And is this the real time tracker?

**Comment by rohitgirdhar** [comment]
This codebase is implemented for humans, but there's no reason for it to be limited to that. The same ideas apply to any object. The speed of the tracker is mostly limited by the detector; our best model used a Resnet-101+FPN based detector, which can be replaced by shallower networks that are much faster.

**Comment by imnaren142** [comment]
So,will using a detector like yolo improve the time significantly  to run in real time?

**Comment by chunniunai220ml** [comment]
@naren142  Have you  improved the time significantly to run in real time by yolo V3? so we should train the model from scratch?
