### ISSUE TITLE
simple way for trying demo

### ISSUE THREAD

**Issue by Sanketyeru** [facebookresearch/DetectAndTrack#19]
1. could you please provide a simple command for trying this system. I do not want to train the model. I would like to Just test it on a video file and see the output. I am using your docker file for this. 
2. I am on the system with the following description:
OS: Ubuntu 16.04
GPU: GTX 1070Ti (8Gb) 
CUDA : 9
cuDNN : 7.0
 
I tried using all_requirements file to create new conda environment but out of them 32 packages are not available for installation. can you provide a working solution for installing this system locally?   
thanks in advance.

**Comment by rohitgirdhar** [comment]
1. is tracked in https://github.com/facebookresearch/DetectAndTrack/issues/6
2. In case the specific versions are not available, you can try running with the latest versions.

**Comment by Sanketyeru** [comment]
Can you please point to the specific file in this repo for only tracking and an example command so as to run tracking without evaluation
