### ISSUE TITLE
Problem in Testing Mode:Getting the error CallWithExceptionIntercept

### ISSUE THREAD

**Issue by imnaren142** [facebookresearch/DetectAndTrack#22]
I0719 20:23:34.495332  4086 net_async_base.cc:435] Using specified CPU pool size: 4; NUMA node id: -1
I0719 20:23:34.495383  4086 net_async_base.cc:440] Created new CPU pool, size: 4; NUMA node id: -1
E0719 20:23:34.497113  4194 net_async_base.cc:368] [enforce fail at conv_op_cudnn.cc:557] filter.dim32(i + 2) == kernel_[i]. 7 vs 1 Error from operator: 
input: "gpu_0/data" input: "gpu_0/conv1_w" output: "gpu_0/conv1" name: "" type: "Conv" arg { name: "kernels" ints: 1 ints: 7 ints: 7 } arg { name: "exhaustive_search" i: 0 } arg { name: "order" s: "NCHW" } arg { name: "pads" ints: 0 ints: 3 ints: 3 ints: 0 ints: 3 ints: 3 } arg { name: "strides" ints: 1 ints: 2 ints: 2 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "CUDNN",  op Conv
WARNING workspace.py: 189: Original python traceback for operator `2` in network `keypoint_rcnn` in exception above (most recent call last):
WARNING workspace.py: 194:   File "tools/test_net.py", line 145, in <module>
WARNING workspace.py: 194:   File "tools/test_net.py", line 106, in main
WARNING workspace.py: 194:   File "/home/Hello/workspace/tracking/DetectAndTrack/lib/core/test_engine.py", line 322, in test_net_on_dataset
WARNING workspace.py: 194:   File "/home/Hello/workspace/tracking/DetectAndTrack/lib/core/test_engine.py", line 135, in test_net
WARNING workspace.py: 194:   File "/home/Hello/workspace/tracking/DetectAndTrack/lib/core/test_engine.py", line 60, in initialize_model_from_cfg
WARNING workspace.py: 194:   File "/home/Hello/workspace/tracking/DetectAndTrack/lib/modeling/model_builder.py", line 61, in create
WARNING workspace.py: 194:   File "/home/Hello/workspace/tracking/DetectAndTrack/lib/modeling/model_builder.py", line 154, in keypoint_rcnn
WARNING workspace.py: 194:   File "/home/Hello/workspace/tracking/DetectAndTrack/lib/modeling/model_builder.py", line 305, in build_generic_fast_rcnn_model
WARNING workspace.py: 194:   File "/home/Hello/workspace/tracking/DetectAndTrack/lib/modeling/model_builder.py", line 951, in build_data_parallel_model
WARNING workspace.py: 194:   File "/home/Hello/workspace/tracking/DetectAndTrack/lib/modeling/model_builder.py", line 197, in _single_gpu_build_func
WARNING workspace.py: 194:   File "/home/Hello/workspace/tracking/DetectAndTrack/lib/modeling/FPN3D.py", line 51, in add_fpn_ResNet101_conv5_body
WARNING workspace.py: 194:   File "/home/Hello/workspace/tracking/DetectAndTrack/lib/modeling/FPN3D.py", line 98, in add_fpn_generic_onto_body
WARNING workspace.py: 194:   File "/home/Hello/workspace/tracking/DetectAndTrack/lib/modeling/ResNet3D.py", line 389, in add_ResNet101_conv5_body
WARNING workspace.py: 194:   File "/home/Hello/workspace/tracking/DetectAndTrack/lib/modeling/ResNet3D.py", line 261, in add_ResNet_convX_body
WARNING workspace.py: 194:   File "/home/Hello/workspace/tracking/anaconda2/envs/detect_and_track/lib/python2.7/site-packages/caffe2/python/cnn.py", line 86, in ConvNd
WARNING workspace.py: 194:   File "/home/Hello/workspace/tracking/anaconda2/envs/detect_and_track/lib/python2.7/site-packages/caffe2/python/brew.py", line 107, in scope_wrapper
WARNING workspace.py: 194:   File "/home/Hello/workspace/tracking/anaconda2/envs/detect_and_track/lib/python2.7/site-packages/caffe2/python/helpers/conv.py", line 164, in conv_nd
WARNING workspace.py: 194:   File "/home/Hello/workspace/tracking/anaconda2/envs/detect_and_track/lib/python2.7/site-packages/caffe2/python/helpers/conv.py", line 123, in _ConvBase
Traceback (most recent call last):
  File "tools/test_net.py", line 145, in <module>
    main(ind_range=args.range, multi_gpu_testing=False)
  File "tools/test_net.py", line 106, in main
    engine.test_net_on_dataset(multi_gpu=multi_gpu_testing)
  File "/home/Hello/workspace/tracking/DetectAndTrack/lib/core/test_engine.py", line 322, in test_net_on_dataset
    all_boxes, all_segms, all_keyps = test_net()
  File "/home/Hello/workspace/tracking/DetectAndTrack/lib/core/test_engine.py", line 160, in test_net
    model, im, box_proposals, timers)
  File "/home/Hello/workspace/tracking/DetectAndTrack/lib/core/test.py", line 907, in im_detect_all
    scores, boxes, im_scales = im_detect_bbox(model, im, box_proposals)
  File "/home/Hello/workspace/tracking/DetectAndTrack/lib/core/test.py", line 197, in im_detect_bbox
    workspace.RunNet(model.net.Proto().name)
  File "/home/Hello/workspace/tracking/anaconda2/envs/detect_and_track/lib/python2.7/site-packages/caffe2/python/workspace.py", line 221, in RunNet
    StringifyNetName(name), num_iter, allow_fail,
  File "/home/Hello/workspace/tracking/anaconda2/envs/detect_and_track/lib/python2.7/site-packages/caffe2/python/workspace.py", line 181, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at conv_op_cudnn.cc:557] filter.dim32(i + 2) == kernel_[i]. 7 vs 1 Error from operator: 
input: "gpu_0/data" input: "gpu_0/conv1_w" output: "gpu_0/conv1" name: "" type: "Conv" arg { name: "kernels" ints: 1 ints: 7 ints: 7 } arg { name: "exhaustive_search" i: 0 } arg { name: "order" s: "NCHW" } arg { name: "pads" ints: 0 ints: 3 ints: 3 ints: 0 ints: 3 ints: 3 } arg { name: "strides" ints: 1 ints: 2 ints: 2 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "CUDNN"

What does this error mean,and how can I resolve this?

**Comment by StalonWilson** [comment]
@naren142 I have the same issue. Did you solve the problem?

**Comment by StalonWilson** [comment]
I think this issue related to if the dimension of the weight is compatible to the used image size.

**Comment by imnaren142** [comment]
@StalonWilson which model you are using for the testing purpose?? I have used the wrong model previously that's why there was in-compatability.

**Comment by StalonWilson** [comment]
@naren142 You are right. I figured out this issue yesterday. Thank you for the kind reply!

**Comment by imnaren142** [comment]
@StalonWilson  Are you working on the training part of this?

**Comment by StalonWilson** [comment]
@naren142 Not yet. I plan to work on the training phase next week because I need more memory space in GPU. Why?

**Comment by imnaren142** [comment]
@StalonWilson casually asking because I am working on it.

**Comment by StalonWilson** [comment]
@naren142 No problem. Did you succeed running training part?

**Comment by imnaren142** [comment]
No....it's taking long with limited resources.

**Comment by StalonWilson** [comment]
I understand...
Now I still stuck on testing my own data...

**Comment by imnaren142** [comment]
How are you doing that?

**Comment by StalonWilson** [comment]
@naren142 Since my data has no annotation, so I set the annotation to empty, like this 

> {"images":[{"is_labeled": false, "width": 1280, "file_name": "00000001.jpg", "height": 720, "frame_id": 1, "original_file_name": "00000001.jpg", "nframes": 3, "id": 1}, {~}, {~}, ~], "annotations": [], "categories": [{"supercategory": "person", "skeleton": [[16, 14], [14, 12], [17, 15], [15, 13], [12, 13], [6, 12], [7, 13], [6, 7], [6, 8], [7, 9], [8, 10], [9, 11], [2, 3], [1, 2], [1, 3], [2, 4], [3, 5], [4, 6], [5, 7]], "id": 1, "keypoints": ["nose", "head_bottom", "head_top", "left_ear", "right_ear", "left_shoulder", "right_shoulder", "left_elbow", "right_elbow", "left_wrist", "right_wrist", "left_hip", "right_hip", "left_knee", "right_knee", "left_ankle", "right_ankle"], "name": "person"}]}

Then I ran the launch.py with test mode, I got the error message as #24 .

Have you been successful to run the test mode with no annotation data?

**Comment by imnaren142** [comment]
No I didn't try to test it with own data.

**Comment by StalonWilson** [comment]
It took a long time to me to understand how to run it properly.
But I still stuck on it.

**Comment by imnaren142** [comment]
Hi @StalonWilson do you know how to train this model on our own data?

**Comment by StalonWilson** [comment]
@naren142  Thank you for asking since I forgot to leave messages here. I haven't tried to train my own data but tested my own data without annotations successfully. So far, I can train the labeled data from PostTrack website. As to my own data..., I guess labelling is the most difficult part. So I don't have any idea of it.

**Comment by imnaren142** [comment]
@StalonWilson  Do you know how to do the annotations part? I didn't get this correctly.

**Comment by StalonWilson** [comment]
@naren142 I used PoseTrack data and its annotations provided by facebookresearch. Its annotations had been provided in repository of this website. I guess if we want to use the data from other sources, we need to first convert our .mat data to .json by `DetectAndTrack/tools/gen_posetrack_json.py` and add the dataset name in `DetectAndTrack/lib/datasets/json_dataset.py`. How do you think?

**Comment by imnaren142** [comment]
@StalonWilson Can you provide your email so that we can be in touch...!!!
