### ISSUE TITLE
Unable to run any example code

### ISSUE THREAD

**Issue by Sanketyeru** [facebookresearch/DetectAndTrack#27]
HI, 
i have tried to run all the example codes like launch.py as well as tools/test_on_one_video.py.

Every time I am getting the same error. 
Traceback (most recent call last):
  File "tools/compute_tracks.py", line 20, in <module>
    from core.config import (
ImportError: cannot import name cfg_from_file

can anyone please help me ?

**Comment by ogata2606** [comment]
I had same issue. And I solved the problem by adding PATH like "export PYTHONPATH=/$DetectAndTrack/lib:$LD_LIBRARY_PATH" to bashrc.

**Comment by Sanketyeru** [comment]
May i know how did you compile and install detectandtrack. i tried all the steps on git page. but it throws the error saying few required packaged from requirement files does not exist.

**Comment by ogata2606** [comment]
I installed along with github Readme.md like you. The required package(cfg_from_file) is in $DetectAndTrack/lib/tools/config.py so, it needs PATH.  Did you through PARH?

**Comment by StalonWilson** [comment]
@Sanketyeru 
I had the same issue before. It disappeared after I copied the "affine_channel" files from ops to caffe2 detectron module folder by using 

`cp lib/ops/affine_channel_nd_op.* caffe2/modules/detectron/`

and recompiled caffe2.

**Comment by chunniunai220ml** [comment]
@rohitgirdhar Have you solved the problem?
I find that the core.config include in lib, and from __future__ import the absolute_import , 
so i  try the line : from lib.core.config import...,  but errors as follow:

Traceback (most recent call last):
  File "tools/compute_tracks.py", line 20, in <module>
    from lib.core.config import (
ImportError: No module named lib.core.config

I don't quite understand the PATH problem, can you share your solution with me?

**Comment by my-hello-world** [comment]
> recompiled caffe2.

hello,help please.
how you recompiled caffe2.?some advices?

Actually I don't want to recompile caffe2 unless there is no other solution. I installed it very hard. hahh
