### ISSUE TITLE
Regarding training mode.

### ISSUE THREAD

**Issue by imnaren142** [facebookresearch/DetectAndTrack#28]
Hi, how to use the downloaded data to train the model? For training we don't have the "PoseTrackV1.0_Annots_val_json" folder?? Can you share the steps to reproduce the training part?

**Comment by StalonWilson** [comment]
@naren142 You may try downloading these files from this [website](https://cmu.box.com/shared/static/gakn52qoxzfzrvmo4c0gfxt4ja1i4g0b.tar). Then, extract them and put them into a new folder `lib/datasets/data/PoseTrackV1.0_Annots_val_json` which created by you.

**Comment by imnaren142** [comment]
@StalonWilson Hey i am talking about "ANN_DN" in  the json_dataset.py file.What should be the value there for training?? For validation part it is the folder "PoseTrackV1.0_Annots_val_json" right?

**Comment by rohitgirdhar** [comment]
As mentioned in the [README](https://github.com/facebookresearch/DetectAndTrack#dataset-and-evaluation), this folder is only required for evaluation. It can have any arbitrary value while training.
