### ISSUE TITLE
[Solved] Environment conflict: Caffe2 Compilation VS Conda Packages

### ISSUE THREAD

**Issue by yanxiangyi** [facebookresearch/DetectAndTrack#31]
Caffe2 compilation requires **system** `protobuf`, `leveldb`, `gflags`, `opencv`, etc rather than those installed from **conda**. Please refer to [this issue](https://github.com/caffe2/caffe2/issues/1980) from `Caffe2`.

According to `README.md`, we install these packages by conda first, and then compile `Caffe2`, which will lead to errors like: 

```
undefined reference to google::protobuf::internal::AssignDescriptors(std::__cxx11::basic_string
undefined reference to leveldb::Status::ToString[abi:cxx11]()
undefined reference to google::protobuf::internal::empty_string_[abi:cxx11]
```

I've solved this problem by:

1. Add `-DCMAKE_CXX_FLAGS=-D__GLIBCXX_USE_CXX11_ABI=0` to the cmake command.

2. Use **system versions** of `gflags`, `protobuf`, `opencv`, or `leveldb` (try installing with `apt-get`). Uninstall these libraries from Anaconda and try to build again.

Finally successfully build on: 

0. Ubuntu 16.04
1. Anaconda (python 2.7)
2. OpenCV 3.4.1
3. GCC 5.4
4. CUDA 9.0
5. cuDNN 7.1.2
6. numpy 1.14.3

**Comment by rohitgirdhar** [comment]
Great, thanks for sharing!
