### ISSUE TITLE
ubuntu16.04 use /tools/test.py subprocess popen wait lock

### ISSUE THREAD

**Issue by mathpopo** [facebookresearch/DetectAndTrack#33]
hi：
    i use ubunt16.04, use test_net.py to test the pretrained model.pkl,when run to subprocess.py ,subprocess popen to get the p and when "log_subprocess_output && i ==0",the p.wait lead to a lock,so "assert ret ==0",who can give me a suggestions?

**Comment by rohitgirdhar** [comment]
The description is unclear. If this is still an issue, please re-open with a clear description of the steps you followed and the error you see.
