### ISSUE TITLE
Range subprocess failed(exit code : 2)

### ISSUE THREAD

**Issue by mathpopo** [facebookresearch/DetectAndTrack#36]
hi ~  i have a issue, could you help me ?
i run the commond in the README.md

'''''bash
python launch.py \
--cfg configs/video/2d_best/01_R101_best_hungarian-4GPU.yaml \
--mode test\
TEST.WEIGHTS pretrained models/configs/video/2d_best/01_R101_best_hungarian-4GPU.yaml/model_final.pkl
'''''''
but it has the log......,  i am using linux ubuntu16.04, and have 4 GPU (TITAN XP 11G)

********* it is log **********
tools/test_net.py: 10: tools/test_net.py: Test a Fafst R-CNN network on an image database: not found
from: cannt read /var/mail/__future__

from: cannt read /var/mail/caffe2.python
tool/test_net.py:21: tools/test_net.py:syntax error;"(" unexpected

Traceback(most recennt call last);
 File "tools/test_net.py", line 143, in <module>
    main(ind_rang=args.range, multi_gpu_testing=args.multi_gpu_testing)
 File "tools/test_net.py", line 104, in main
   engine.test_net_on_dataset(multi_gpu=multi_gpu_testing)
 File "data/DetectAndTrack/lib/core/test_engine.py", line 319, in test_net_on_dataset
    num_images, output_dir)
 File "data/DetectAndTrack/lib/core/test_engine.py", line 284, in multi_gpu_test_net_on_dataset
   'detection' , num_images, binary, output_dir
 File "data/DetectAndTrack/lib/utils/subprocess.py", line 67, in process_in_parallel
  log_subprocess_output(i, p, output_dir, tag, start, end)
 File "data/DetectAndTrack/lib/utils/subprocess.py", line 97, in log_subprocess_output
  assert ret == 0, 'Range subprocess failed (exit code: {})'.format(ret)
AssertionError:Range subprocess failed(exit code : 2)
****************************

**Comment by mathpopo** [comment]
and i have run track commonds , they are OK, only test have the issue

**Comment by mathpopo** [comment]
use command like below,all is right.
python launch.py 
--cfg configs/video/2d_best/01_R101_best_hungarian-4GPU.yaml 
--mode track
......

**Comment by ezreal1129** [comment]
@mathpopo  can you fixed it?

**Comment by mathpopo** [comment]
@ezreal1129 sorry,not deal with it,if you have any idea,plz tell me,thanks!

**Comment by my-hello-world** [comment]
@mathpopo  @ezreal1129 
python launch.py -c configs/video/2d_best/01_R101_best_hungarian-4GPU.yaml -m test USE_NCCL True

The error disappeared ,This will require Caffe2 to have been built with nccl ops
