### ISSUE TITLE
offending key: affineChannelNd

### ISSUE THREAD

**Issue by mathpopo** [facebookresearch/DetectAndTrack#37]
when i run the test_on_sigle_video.py in README

it has a issue;

```
found Detectron ops lib: /usr/local/lib/libcaffe2_detectron_ops_gpu.so
key already registerd
offending key; AffineChannelNd.
```

sorry !  i don't know why

**Comment by rohitgirdhar** [comment]
Please refer to steps suggested in previous issues regarding this, eg. https://github.com/facebookresearch/DetectAndTrack/issues/20, https://github.com/facebookresearch/DetectAndTrack/issues/27#issuecomment-409453279
