### ISSUE TITLE
Testing Pre-Trained Models

### ISSUE THREAD

**Issue by yannadani** [facebookresearch/DetectAndTrack#4]
The following command does not seem to work atm because of the absence of the `best_model.pkl` file inside the `01_R101_best_hungarian.yaml` folder of `pretrained_models`. 
`
python launch.py \
	--cfg configs/video/2d_best/01_R101_best_hungarian-4GPU.yaml \
	--mode test \
	TEST.WEIGHTS pretrained_models/configs/video/2d_best/01_R101_best_hungarian.yaml/model_final.pkl
`

Do you suggest to use the 4-GPU one or can we expect a `best_model.pkl` file ? 
Thanks for the code and kudos on a very nice work!

**Comment by rohitgirdhar** [comment]
Thanks for your interest! I have added the model. Unfortunately I didn't have time to test it, so please let me know in case it doesn't work as expected. In any case, the 4GPU model produces slightly higher performance, so you can always use that.
