### ISSUE TITLE
Finetune on custom dataset

### ISSUE THREAD

**Issue by yanxiangyi** [facebookresearch/DetectAndTrack#41]
Hi @rohitgirdhar, we can now run the code (both training and inference) perfectly on posetrack dataset. Thanks for this repo!

Currently, we would like to train the model on our custom dataset, which has different number of keypoints and photo sizes. We don't accutually want to train it from scratch. Could you please offer us some suggestions? Thanks!

**Comment by yanxiangyi** [comment]
Problem solved. I will update this issue few days later.

**Comment by meetdave06** [comment]
@yanxiangyi  I am also trying to do something similar. Could you please share your approach?

**Comment by kathanvyas** [comment]
> Problem solved. I will update this issue few days later.

hey @yanxiangyi could you please share how you did that? we are trying to do the same however we are running into some errors. I would appreciate your help.
