### ISSUE TITLE
py-motmetrics

### ISSUE THREAD

**Issue by cheind** [facebookresearch/DetectAndTrack#44]
Hi, very nice work! Just discovered that deeply in your code you are refering to this library for pose evaluation  https://github.com/cheind/py-motmetrics. Which happens to be a library of mine. It seems like you got it via https://github.com/leonid-pishchulin/poseval/, who refers to it via a submodule. This referall has been lost in your code copy. Would you mind noting a link to the original repository in the `Dataset and Evaluation` section?

**Comment by rohitgirdhar** [comment]
Sure, done.

**Comment by cheind** [comment]
Thanks! One thought: you are mentioning a multi-process optimization for faster processing. Not sure what the slow part of the evaluation was, but py-motmetrics supports different solvers for LAP problems. By default scipy is used, but faster variants such as https://github.com/cheind/py-lapsolver are available. In case you want to try out, just `pip install lapsolver` and re-run your evaluation.
