### ISSUE TITLE
about the test

### ISSUE THREAD

**Issue by ezreal1129** [facebookresearch/DetectAndTrack#46]
1. My data is only ground truth, no keypoints.so can i test the pre-model?
2. The key point of the data results is how to form the boundingbox data, because I can only use the boundingbox to evaluate.

**Comment by rohitgirdhar** [comment]
Yes, please try [`tools/test_on_single_video.py`](../tree/master/tools/test_on_single_video.py) to test pretrained models, which doesn't need any GT annotation.

**Comment by ezreal1129** [comment]
@rohitgirdhar  Thank you ,but  how should i evaluate the rusult of test_on_single_video.py
