### ISSUE TITLE
PackagesNotFoundError: The following packages are not available from current channels: - libiconv==1.15=0

### ISSUE THREAD

**Issue by Duankaiwen** [facebookresearch/DetectAndTrack#48]
**conda create -c conda-forge --name $ENV_NAME --file all_pkg_versions.txt python=2.7 anaconda**
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - libiconv==1.15=0

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/linux-64
  - https://repo.anaconda.com/pkgs/pro/noarch

**Comment by rohitgirdhar** [comment]
Please try a newer version of the package. The provided list is only a reference, the code should ideally be compatible with the newer versions as well.

**Comment by Duankaiwen** [comment]
> Please try a newer version of the package. The provided list is only a reference, the code should ideally be compatible with the newer versions as well.
Many thanks！

**Comment by my-hello-world** [comment]
hello
i try  `conda install libiconv` in the env. Got  libiconv==1.14。
but i got new problems after changed it.
`Solving environment: failed
 
UnsatisfiableError: The following specifications were found to be in conflict:
  - blas==1.1=openblas
  - numexpr==2.6.4=py27hd318778_0 -> blas=[build=mkl]
Use "conda info <package>" to see the dependencies for each package.`

 As suggested, by the error prompt, I can view more details with conda info,doing this：
`conda info numexpr==2.6.4`
I compared them with all_pkg_versions.txt  carefully，but  still can't see a conflict. 
try again：
`conda create -c conda-forge --name $ENV_NAME --file all_pkg_versions.txt python=2.7 anaconda`
i got：
`Solving environment: failed
 
UnsatisfiableError: The following specifications were found to be in conflict:
  - numexpr==2.6.4=py27hd318778_0
  - opencv==3.4.1=py27_blas_openblas_200
Use "conda info <package>" to see the dependencies for each package.
`
ahahahhh
How can I deal with this? 
thanks！

**Comment by Duankaiwen** [comment]
> hello
> i try `conda install libiconv` in the env. Got libiconv==1.14。
> but i got new problems after changed it.
> `Solving environment: failed
> 
> UnsatisfiableError: The following specifications were found to be in conflict:
> 
> * blas==1.1=openblas
> * numexpr==2.6.4=py27hd318778_0 -> blas=[build=mkl]
>   Use "conda info " to see the dependencies for each package.`
> 
> As suggested, by the error prompt, I can view more details with conda info,doing this：
> `conda info numexpr==2.6.4`
> I compared them with all_pkg_versions.txt carefully，but still can't see a conflict.
> try again：
> `conda create -c conda-forge --name $ENV_NAME --file all_pkg_versions.txt python=2.7 anaconda`
> i got：
> `Solving environment: failed
> 
> UnsatisfiableError: The following specifications were found to be in conflict:
> 
> * numexpr==2.6.4=py27hd318778_0
> * opencv==3.4.1=py27_blas_openblas_200
>   Use "conda info " to see the dependencies for each package.
>   `
>   ahahahhh
>   How can I deal with this?
>   thanks！

Try to comment the package ‘numexpr’, then run the code, if the code can still work fine, the problem can be ignored. I've encountered similar problems, and comment some problematic packages, I found the code still works fine. If this doesn't work, you'd better use libiconv=1.15=0. Good luck!
