### ISSUE TITLE
2d_best model using FPN3D

### ISSUE THREAD

**Issue by guohengkai** [facebookresearch/DetectAndTrack#5]
Hi,

In your yaml files in 2d_best, the conv body of model is "FPN3D.add_fpn_ResNet101_conv5_body". Is there something wrong with it?

Thanks!

**Comment by guohengkai** [comment]
And the model_final.pkl is also the 3D model, which uses 7x7 kernel in the first layer.

**Comment by rohitgirdhar** [comment]
It is just implemented using a 3D conv operation. The time dimension of that kernel is 1 (VIDEO.TIME_KERNEL_DIM = 1 in the config), which effectively makes the kernel 2D.

**Comment by zyxforever** [comment]
Excuse me，I think the  final feature map output of the base 3D network for a T*H*W input is T*H/16*W/16 after 4 residual block. What's wrong with me?
