### ISSUE TITLE
Detection and Tracking without Evaluation

### ISSUE THREAD

**Issue by RomeroBarata** [facebookresearch/DetectAndTrack#6]
Hi,

Is it possible to extract the detected key points and tracking information without evaluating performance of the model? I'd like to use Detect and Track on a data set for which I don't have the ground-truth annotations. Thank you!

**Comment by yannadani** [comment]
In addition to this, can you give pointers to detect keypoints and track them for a single video? Thanks.

**Comment by yannadani** [comment]
Ok, I have written a script which can now detect and track for a single video, without evaluating it. I can share it if lot of people require it.

**Comment by RomeroBarata** [comment]
I think that it would be great if you could share it @yannadani!

**Comment by rohitgirdhar** [comment]
Please feel free to open a pull request if you'd like! Thanks!

**Comment by msarmiento3** [comment]
It will be amazing @yannadani!

**Comment by yannadani** [comment]
Cool. I will submit a PR around this weekend when I'm free.

**Comment by jpdz** [comment]
@yannadani  Hi, I am really interested in how to detect and track for a single video, without evaluating it, can you share the scripts? Really appreciated!

**Comment by jpdz** [comment]
Hi, I have questions about how to do real time tracking.
According to my understanding, we should first detect all of the persons in the image set, storing the model into the pickle file called 'detection.pkl'. And then we run the tracking code and store the tracking result into 'detection.tracking.pkl'. It seems like the two things can not happen synchronously. Is my understanding wrong? Thanks a lot.

**Comment by rohitgirdhar** [comment]
Yes they can. The tracking can be done online, with the detector running frame by frame, and the tracker linking the tracks to the previous frame.

**Comment by Sanketyeru** [comment]
Does anyone know where is code for **"detect and track for a single video, without evaluating it"**.?@yannadani, could you please share your code for detection and tracking without evaluation. 

Thanks.

**Comment by rohitgirdhar** [comment]
#25 #26 resolve this issue.
