### ISSUE TITLE
There's no eigen repository

### ISSUE THREAD

**Issue by paolomanchisi** [facebookresearch/DetectAndTrack#7]
'https://github.com/RLovelett/eigen.git/
does not exists

Thank you.

**Comment by rohitgirdhar** [comment]
I am not sure how it is related to this codebase. Can you point how you run into this error?

**Comment by kenny-kong-facemo** [comment]
I think we need eigen.git to build caffe2 from source.

**Comment by rohitgirdhar** [comment]
That's a caffe2 issue. Please follow https://github.com/caffe2/caffe2/pull/2525 for updates.
