### ISSUE TITLE
Question ahout your paper

### ISSUE THREAD

**Issue by lxtGH** [facebookresearch/DetectAndTrack#71]
Hi! Thanks for your repo. I have serveral question.
1. The best performance in the paper is 2D-Mask-RCNN not 3D-mask-rcnn?
2. In table6, what are results of 3D-Mask-RCNN with ResNet50/101 as Backbone?

**Comment by rohitgirdhar** [comment]
Hi, thanks for your interest.
1. Overall compared to state of the art, yes.
2. No, those are with ResNet 18 (says in the caption).
