### ISSUE TITLE
caffe2  does not have detectron module

### ISSUE THREAD

**Issue by ks322181** [facebookresearch/DetectAndTrack#75]
I tried to install caffe2 through pytorch. caffe is installing, When i am checking it is giving caffe is True. But caffe2 does not have detectron module.

make ops is throwing an error. So i wanted to copy file from lib to caffe2/module/detectron. But i didn't find it any where. Can anyone help me to resolve this..

Thanks in Advance

**Comment by williamdwl** [comment]
I have the same problem，Do you solve the problem？ I need help

**Comment by williamdwl** [comment]
I salved by modified the following step:
first step:
find where is libcaffe2_detectron_ops_gpu.so
```shell
sudo find / -name libcaffe2_detectron_ops_gpu.so
```
then I modify the env.py by

```python
prefixes = [_CMAKE_INSTALL_PREFIX, sys.prefix, sys.exec_prefix] + sys.path + ['/path/to/ libcaffe2_detectron_ops_gpu.so']
```

**Comment by ks322181** [comment]
> I salved by modified the following step:
> first step:
> find where is libcaffe2_detectron_ops_gpu.so
> 
> ```shell
> sudo find / -name libcaffe2_detectron_ops_gpu.so
> ```
> 
> then I modify the env.py by
> 
> ```python
> prefixes = [_CMAKE_INSTALL_PREFIX, sys.prefix, sys.exec_prefix] + sys.path + ['/path/to/ libcaffe2_detectron_ops_gpu.so']
> ```

Hi,

Were you able to execute it . I have tried this but it still didn't fixed my error.

**Comment by ks322181** [comment]
Are you able to run the algorithm?
