### ISSUE TITLE
[Question] cls and reg loss of the TPN are same with loss layers of the Classification Head?

### ISSUE THREAD

**Issue by aFewThings** [facebookresearch/DetectAndTrack#77]
Hi, I have a question about the paper. 
At Fig 2., It seems that losses of TPN and Classification Head are same.
If they are not, what is the purpose of Classification Head?

**Comment by rohitgirdhar** [comment]
Hi, the losses are not exactly the same; they are comparable to how the losses in stage 1 (RPN) and stage 2 (classification/bounding box regression) in mask r-cnn are defined. I'd recommend looking at [Mask R-CNN](https://arxiv.org/abs/1703.06870) or [Faster R-CNN](https://arxiv.org/abs/1506.01497) for more details.

**Comment by aFewThings** [comment]
Thx, but I still have question.
In the Faster R-CNN, the Classification Head had cls and reg layer which were for refining bbox and classifying categories of objects.
If so, why 3D Mask R-CNN still have cls layer to classify categories of objects like the Faster R-CNN for object classification? 
Isn't it enough to have the Keypoints Head for pose estimation or tracking task?
